[tool.poetry]
name = "bencode2"
version = "0.0.1"
description = "Example project for demonstrating proprietary PyPI packages"
authors = ["Aotu"]
license = "Proprietary"
readme = "readme.md"

# Only include cythonized files in final build
include = ["bencode2/**/*.so"]  # ignored in VCS, so we need to be explicit
exclude = ["bencode2/**/*.py"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
Cython = "^0.29.21"
pytest = '~7'

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools~=50.3.2", 'cython==0.29.37']
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
# The allows us to build C extensions (using Cython). Unstable feature
# https://github.com/python-poetry/poetry/issues/2740#issuecomment-666551481
script = "build.py"
generate-setup-file = false