version: 2.1

executors:
  my-executor:
    resource_class: arm.medium
    machine:
      image: ubuntu-2204:current
    working_directory: .


commands:
  build:
    parameters:
      build:
        type: string
      build_config:
        type: string
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install cibuildwheel
          command: python -m pip install cibuildwheel --no-color --progress-bar=off
      - run:
          name: Run cibuildwheel
          command: python -m cibuildwheel --output-dir ./wheelhouse
          environment:
            CIBW_BUILD_VERBOSITY: '1'
            CIBW_BUILD_FRONTEND: "build[uv]"
            CIBW_ARCHS: aarch64
            CIBW_BUILD: "<<parameters.build>>"
            CIBW_CONFIG_SETTINGS: "<<parameters.build_config>>"
            CIBW_TEST_REQUIRES: pytest
            CIBW_TEST_COMMAND: "pytest {project}/tests --assert-pkg-compiled=true"

      - persist_to_workspace:
          root: .
          paths:
            - ./wheelhouse

jobs:
  build-and-test-1:
    executor: my-executor
    steps:
      - build:
          build: "*[02468]-* *[02468]t-*"
          build_config: ''

  build-and-test-2:
    executor: my-executor
    steps:
      - build:
          build: "*[13579]-* *[13579]t-*"
          build_config: ''

  build-and-test-abi3:
    executor: my-executor
    steps:
      - build:
          build: "*cp312-*"
          build_config: 'setup-args="-Dabi3=enabled"'

  check:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - run: python -m pip install twine --no-color --progress-bar=off
      - run: python -m twine check ./wheelhouse/*

  pypi:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .

      - run: pip install twine --no-color --progress-bar=off
      - run: >-
          python -m twine upload
          --non-interactive --disable-progress-bar
          --username __token__ --password "${PYPI_TOKEN}"
          ./wheelhouse/*.whl

workflows:
  ci:
    jobs:
      - build-and-test-1:
          filters:
            tags:
              only: /^v.*/
      - build-and-test-2:
          filters:
            tags:
              only: /^v.*/
      - build-and-test-abi3:
          filters:
            tags:
              only: /^v.*/
      - check:
          requires:
            - build-and-test-1
            - build-and-test-2
            - build-and-test-abi3
          filters:
            tags:
              only: /^v.*/
      - pypi:
          requires:
            - check
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
