name: Reusable workflow example

on:
  workflow_call:

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { os: macos-13, arch: x86_64, build: "*", triplet: 'x64-osx' }
          - { os: macos-13, arch: arm64, build: "*", triplet: 'arm64-osx' }
          - { os: windows-latest, arch: AMD64, build: "*" }
          - { os: ubuntu-latest, arch: x86_64, build: "*t-*", triplet: 'x64-linux' }
          - { os: ubuntu-latest, arch: x86_64, build: "*[02468]-*", triplet: 'x64-linux' }
          - { os: ubuntu-latest, arch: x86_64, build: "*[13579]-*", triplet: 'x64-linux' }
          - { os: ubuntu-latest, arch: aarch64, build: "*t-manylinux*", triplet: 'aarch64-linux' }
          - { os: ubuntu-latest, arch: aarch64, build: "*t-musllinux*", triplet: 'aarch64-linux' }
          - { os: ubuntu-latest, arch: aarch64, build: "*[05]-manylinux*", triplet: 'aarch64-linux' }
          - { os: ubuntu-latest, arch: aarch64, build: "*[16]-manylinux*", triplet: 'aarch64-linux' }
          - { os: ubuntu-latest, arch: aarch64, build: "*[27]-manylinux*", triplet: 'aarch64-linux' }
          - { os: ubuntu-latest, arch: aarch64, build: "*[38]-manylinux*", triplet: 'aarch64-linux' }
          - { os: ubuntu-latest, arch: aarch64, build: "*[49]-manylinux*", triplet: 'aarch64-linux' }
          - { os: ubuntu-latest, arch: aarch64, build: "*[05]-musllinux*", triplet: 'aarch64-linux' }
          - { os: ubuntu-latest, arch: aarch64, build: "*[16]-musllinux*", triplet: 'aarch64-linux' }
          - { os: ubuntu-latest, arch: aarch64, build: "*[27]-musllinux*", triplet: 'aarch64-linux' }
          - { os: ubuntu-latest, arch: aarch64, build: "*[38]-musllinux*", triplet: 'aarch64-linux' }
          - { os: ubuntu-latest, arch: aarch64, build: "*[49]-musllinux*", triplet: 'aarch64-linux' }
    steps:
      - uses: docker/setup-qemu-action@v3
        if: matrix.os == 'ubuntu-latest'

      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: enable vcpkg
        if: matrix.os == 'windows-latest'
        run: ${{ github.workspace }}/vcpkg/vcpkg install

      - name: Restore cached Primes
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\pypa\cibuildwheel\Cache
            ~/Library/Caches/cibuildwheel
            ~/.cache/cibuildwheel
          key: 'cibuildwheel-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.build }}'
          restore-keys: |
            cibuildwheel-${{ runner.os }}-${{ matrix.arch }}

      - uses: pypa/cibuildwheel@v2.21.3
        env:
          TRIPLET: ${{ matrix.triplet }}
          CIBW_ENVIRONMENT_PASS_LINUX: TRIPLET
          CIBW_BUILD_VERBOSITY: 1
          CIBW_FREE_THREADED_SUPPORT: true
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_SKIP: 'pp*'
          CIBW_BUILD_FRONTEND: 'build'
          MACOSX_DEPLOYMENT_TARGET: '11.0'
          CIBW_BEFORE_ALL_WINDOWS: >
            C:\vcpkg\bootstrap-vcpkg.bat &&
            C:\vcpkg\vcpkg integrate install


      - run: ls ./wheelhouse/

      - uses: actions/upload-artifact@v4
        with:
          name: 'wheels-${{ runner.os }}-${{ matrix.arch }}-${{ strategy.job-index }}'
          path: ./wheelhouse/*.whl

  build:
    name: make sdist and wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx run build
        env:
          PY_BENCODE2_PURE_PYTHON: '1'

      - uses: actions/upload-artifact@v4
        with:
          name: 'wheels-dist'
          path: dist/*
