name: Build Wheels for PyPI

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true  # Optional, use if you have submodules

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4.3.1
      with:
        path: dist/*.tar.gz

  build_other_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.17.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  check_dist:
    name: Check dist
    needs: [make_sdist, build_other_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.4
        with:
          name: artifact
          path: dist

      - run: pipx run twine check --strict dist/*

  upload_all:
    name: Upload wheels to PyPI
    needs: [build_other_wheels, make_sdist, check_dist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4.1.4
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          #! Update with your project's PyPI API Token Name!
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
